### ISSUE TITLE
Suggestion: add flag option in right-click menu

### ISSUE THREAD

**Issue by Menno5** [chromium/suspicious-site-reporter#59]
To report a site, you *must* to be on that site. But a lot of sites found through Google Search are clearly suspicious or malicious and you do not want to go there ... so it can not be flagged/reported.
Suggestion: make an option to flag that in the right-click menu of the browser. This way a suspicious or malicious site can be reported without endangering yourself by visiting it.

**Comment by ericlaw1979** [comment]
You can use https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en to report phishing sites in general without visiting them.

As a rule, Chrome is designed to safely load any web page. If you suspect a site is a phishing page, you are safe if you simply avoid entering any personal information into the page.

The suspicious site reporter is designed to report phishing pages, and provide additional information (including IP address and screenshots) which can combat phish that otherwise "cloak" themselves against detection by Google.

**Comment by livvielin** [comment]
+1 to Eric's comment above. I'm closing this issue since https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en is the right place to go for reporting suspicious/malicious sites without visiting them, rather than using this extension.
